using System.Collections.Generic;
using VehicleVisionOCR.Backend.Services.OcrCorrection.Enums;

namespace VehicleVisionOCR.Backend.Services.OcrCorrection.Models
{
    /// <summary>
    /// Represents the finalized, rich output of an OCR correction strategy.
    /// Contains full traceability of the original text, applied normalization rules, and validation scoring.
    /// </summary>
    public class CorrectionResult
    {
        /// <summary>
        /// The raw, unadulterated text as emitted by the underlying OCR engine.
        /// Preserved strictly for debugging and traceability.
        /// </summary>
        public string OriginalText { get; set; } = string.Empty;

        /// <summary>
        /// The finalized string after candidate generation and pattern scoring.
        /// </summary>
        public string CorrectedText { get; set; } = string.Empty;

        /// <summary>
        /// Indicates whether the final CorrectedText passed all mandatory business validations (e.g., ISO 3779 Math).
        /// </summary>
        public bool IsValid { get; set; }

        /// <summary>
        /// True if the correction pipeline fundamentally altered the OriginalText (e.g., S -> 5).
        /// False if the OriginalText was deemed perfect and passed through unchanged.
        /// </summary>
        public bool WasCorrected { get; set; }

        /// <summary>
        /// The composite score generated by the scoring service evaluating confidence, pattern, and business constraints.
        /// </summary>
        public double FinalScore { get; set; }

        /// <summary>
        /// A calculated classification of the FinalScore designed to simplify UI rendering and human review queues.
        /// </summary>
        public ConfidenceLevel ConfidenceLevel { get; set; }

        /// <summary>
        /// The fully qualified name of the strategy that generated this result (e.g., VinCorrectionStrategy).
        /// </summary>
        public string StrategyName { get; set; } = string.Empty;

        /// <summary>
        /// A sequential audit trail of all normalization, tokenization, and character confusion rules applied to the text.
        /// </summary>
        public List<string> AppliedRules { get; set; } = new();

        /// <summary>
        /// A human-readable explanation of why the result was flagged as IsValid = false (if applicable).
        /// Null if the result is valid.
        /// </summary>
        public string? FailureReason { get; set; }
    }
}
